version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pz_postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pizzeria
      - POSTGRES_DB=pizzeria
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: pizzeria
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local